### PR TITLE
Improve OO C++ interface

### PR DESCRIPTION
**Pull request by felixhekhorn**
Improvements from actual usage:
- expose `scale` and `optimize`

### CODE REVIEW

**Review by cschwan — CHANGES_REQUESTED** [review]
Can you please make the periods consistent? Some sentences and with a period, some without. Otherwise this LGTM.

**Comment by cschwan** [comment]
We should be able to install the static header using the configuration file changes described in [`cargo-c`'s README](https://github.com/lu-zero/cargo-c?tab=readme-ov-file#custom-data-install), using `asset` in `[package.metadata.capi.install.include]`, but my first try was unsuccessful. Let me check why.

**Comment by alecandido** [comment]
Small advice: use lowercase names for files, to avoid potential issues with case sensitivity.
(feel free to ignore)

**Comment by felixhekhorn** [comment]
> Can you please make the periods consistent? Some sentences and with a period, some without. Otherwise this LGTM.

Done in e72a5d6

**Comment by cschwan** [comment]
> Is there any chance to have `PineAPPL.hpp` be delivered next to `pineappl_capi.h` by default?

This is implemented in commit 422d6723ea3d1ee57f2db3f386ea40332f9c97fe.

**Pull request merged**
